import csv
from pathlib import Path

from rdkit import Chem

ROOT = Path(__file__).resolve().parent
# The stage scripts fall back to molecule-fg-data/pubchem_like_sample_120.csv when
# smiles.json is missing, so write it there.
OUT_PATH = ROOT / 'pubchem_like_sample_120.csv'

# A synthetic PubChem-like sample set with a mix of small, medium, and more complex molecules.
SMILES_LIST = [
    'CN(C)C1=CC=C(C=C1)N=NC2=CC=C(C=C2)C#C',
    'CC(C)(C)C(=O)C=C(C1=CC=CC=C1)NC2=CC=CC=C2',
    'COC1[C@@H]([C@H]([C@@H]([C@H](O1)COC(=O)/C=C/C2=CC(=C(C(=C2)OC)OCC=C)OC)O)O)O',
    'CCN(CC)CCC1=C2C3=CC=CC=C3CN2C4=C1C=C(C=C4)Br',
    'CC1=C(N(C(=N1)C2=CC(=C(C=C2OC)NC(=O)C)[N+](=O)[O-])O)C3=CN=CC=C3',
    'CCC',
    'CCO',
    'CCN',
    'CC(=O)O',
    'c1ccccc1',
    'CC=CC',
    'C1=CC=CC=C1',
    'CCOC(=O)C',
    'CS(=O)(=O)O',
    'C1CCCCC1',
    'NCCO',
    'NC(=O)N',
    'CCCl',
    'CCBr',
    'CCF',
    'C1=CC=CNC=C1',
    'O=C(O)C1=CC=CC=C1',
    'CNC',
    'CN(C)C',
    'c1nccnc1',
    'CCS',
    'CCSSCC',
    'OC(CO)CO',
    'CC(=O)NC',
    'OC1=CC=CC=C1',
    'c1ccc2ccccc2c1',
    'CC(=O)OCC',
    'CC(C)O',
    'CC(C)N',
    'C1CCNCC1',
    'c1ccncc1',
    'CC(=O)N',
    'CC(=O)C',
    'CC(=O)OC',
    'CC(=O)NCC',
    'CC(=O)OCCO',
    'COC(=O)C',
    'COC(=O)OC',
    'C=CC=C',
    'C=CC#N',
    'CC(=O)C=C',
    'CC#N',
    'CC(C)C',
    'CCC(C)C',
    'CCCCCC',
    'C1=CC=CC=C1O',
    'C1=CC=C(C=C1)C(=O)O',
    'CNC(=O)N',
    'N1C=NC=N1',
    'O=P(O)(O)O',
    'COP(=O)(O)OC',
    'c1ccc(Cl)cc1',
    'c1ccc(Br)cc1',
    'c1ccc(F)cc1',
    'c1ccc(I)cc1',
    'c1ccccc1O',
    'c1ccccc1S',
    'c1ccccc1N',
    'c1ccccn1',
    'c1ccsc1',
    'O=C1NCCN1',
    'O=C1NC=CC=C1',
    'O=C1NC=CC=C1O',
    'C1CC(=O)NC1',
    'C1CCN(C1)C',
    'C1NCCN1',
    'C1CCSC1',
    'CSCCO',
    'C1CCOC1',
    'C1CCSCC1',
    'C1CCNCC1O',
    'C1CCC(=O)NC1',
    'C1CCSC(=O)C1',
    'CC1=CC=CC=C1',
    'CC1CCC=CC1',
    'O=CC1=CC=CC=C1',
    'O=C(C1=CC=CC=C1)O',
    'O=C1NC(=O)NC(=O)1',
    'N1C=NC2=NC=NC=C12',
    'COc1ccccc1',
    'COc1ccccc1OC',
    'COc1ccc(N)cc1',
    'Oc1ccc(O)cc1',
    'Oc1ncccc1',
    'CCN(CC)CC',
    'CCN(CC)CCO',
    'CCN(CC)CCN',
    'CCN(CC)CCCl',
    'CCN(CC)CCBr',
    'CCN(CC)C(=O)N',
    'CCN(CC)C(=O)O',
    'CCN(CC)S(=O)(=O)N',
    'CCN(CC)C=C',
    'CCN(CC)C#N',
    'CCN(CC)C(=O)C',
    'CCN(CC)C(=O)NC',
    'CCN(CC)C(=O)OCC',
    'C=CC(O)C',
    'C=CC(O)CO',
    'C=CC(C)O',
    'CC=CCO',
    'CC=CCN',
    'CC=CCCl',
    'CC=CCBr',
    'CC=CCF',
    'CC=CCS',
    'COC1=CC=CC=C1',
    'COC1=CC=C(C=C1)C=O',
    'COC1=C(C=CC=C1)C(=O)O',
    'COC1=CC=C(C=C1)N',
    'COC1=CC=C(C=C1)N(C)C',
    'CCOC1=CC=CC=C1',
    'CCOC1=CC=C(C=C1)O',
    'CCOC1=CC=C(C=C1)N',
    'CCOC1=CC=C(C=C1)C=O',
    'COC1=CC=CC(=C1)C(=O)O',
    'CC1=CC(=CC=C1)C(=O)O',
    'COC(=O)C1=CC=CC=C1',
    'COC(=O)C1=CC=C(C=C1)N',
    'C1=CC=CC=C1C(=O)N',
    'N#CC1=CC=CC=C1',
    'N#CC1=CC=C(C=C1)O',
    'N#CC1=CC=C(C=C1)N',
    'N#CC1=CC=C(C=C1)Cl',
    'N#CC1=CC=C(C=C1)Br',
    'N#CC1=CC=C(C=C1)F',
    'N#CC1=CC=C(C=C1)S',
    'C1=CC=CC=C1C#N',
    'Cc1ccccc1',
    'Cc1ccccc1O',
    'Cc1ccccc1N',
    'Cc1ccccc1Cl',
    'Cc1ccccc1Br',
    'Cc1ccccc1F',
    'C[C@H](O)C1=CC=CC=C1',
    'C[C@@H](O)C1=CC=CC=C1',
    'C[C@@H](N)C1=CC=CC=C1',
    'C[C@H](N)C1=CC=CC=C1',
    'CC[C@H](N)C(=O)O',
    'CC[C@@H](N)C(=O)O',
    'CC[C@H](O)C(=O)O',
    'CC[C@@H](O)C(=O)O',
]

assert 100 <= len(SMILES_LIST) <= 150, f'Expected 100-150 molecules, got {len(SMILES_LIST)}'

valid = []
for i, smi in enumerate(SMILES_LIST, start=1):
    mol = Chem.MolFromSmiles(smi)
    if mol is None:
        raise ValueError(f'Invalid SMILES at index {i}: {smi}')
    valid.append((i, smi))

OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
with OUT_PATH.open('w', newline='') as fh:
    writer = csv.writer(fh)
    writer.writerow(['cid', 'smiles'])
    writer.writerows(valid)

print(f'Wrote {len(valid)} molecules to {OUT_PATH}')
